# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
# Python type hints target Python 3.11+.

import builtins
import typing
__all__ = [
    "PIIDetectorRust",
]

DetectionItem = dict[str, typing.Any]
DetectionsByType = dict[str, list[DetectionItem]]

@typing.final
class PIIDetectorRust:
    r"""
    Main PII detector exposed to Python

    # Example (Python)
    ```python
    from pii_filter_rust import PIIDetectorRust

    config = {"detect_ssn": True, "detect_email": True}
    detector = PIIDetectorRust(config)

    text = "My SSN is 123-45-6789 and email is john@example.com"
    detections = detector.detect(text)
    print(detections)  # {"ssn": [{"value": "123-45-6789", "start": 10, "end": 21, "mask_strategy": "partial", "description": "US Social Security Number"}], "email": [{"value": "john@example.com", "start": 35, "end": 51, "mask_strategy": "partial", "description": "Email address"}]}

    masked = detector.mask(text, detections)
    print(masked)  # "My SSN is ***-**-6789 and email is j***n@example.com"
    ```
    """
    def __new__(cls, config: typing.Any) -> PIIDetectorRust:
        r"""
        Create a new PII detector

        # Arguments
        * `config` - Python dictionary or Pydantic model with configuration

        # Configuration Keys
        * `detect_ssn` (bool): Detect Social Security Numbers
        * `detect_credit_card` (bool): Detect credit card numbers
        * `detect_email` (bool): Detect email addresses
        * `detect_phone` (bool): Detect libphonenumber-validated U.S. domestic formats and international numbers with country code
        * `detect_ip_address` (bool): Detect IPv4 and standard fully expanded or compressed IPv6 addresses
        * `detect_date_of_birth` (bool): Detect dates of birth with DOB or birth-date style context
        * `detect_passport` (bool): Detect U.S. (9 digits) and EU-style (2 letters + 7 digits) passport numbers with passport label or U.S. / EU region marker
        * `detect_driver_license` (bool): Detect driver license numbers for CA, TX, FL, and NY with driver-license label or state marker
        * `detect_bank_account` (bool): Detect contextual 8-17 digit bank account numbers and checksum-validated IBAN
        * `detect_medical_record` (bool): Detect contextual MRN / Medical Record identifiers
        * `detect_us_aba_routing_number` (bool): Detect 9-digit U.S. ABA routing transit numbers that satisfy prefix and checksum rules
        * `default_mask_strategy` (str): "auto" (alias: "default"), "redact", "partial", "hash", "tokenize", "remove"
        * `redaction_text` (str): Text to use for redaction (default: "\[REDACTED\]")
        * `block_on_detection` (bool): Whether to error instead of masking when PII is found
        * `log_detections` (bool): Whether to log detections to stderr
        * `include_detection_details` (bool): Whether to include descriptions in detection results
        * `whitelist_patterns` (list[str]): Regex patterns to exclude from detection
        """
    def detect(self, text: builtins.str) -> DetectionsByType:
        r"""
        Detect PII in text

        # Arguments
        * `text` - Text to scan for PII

        # Returns
        Dictionary mapping PII type to list of detections:
        ```python
        {
            "ssn": [
                {"value": "123-45-6789", "start": 10, "end": 21, "mask_strategy": "partial"}
            ],
            "email": [
                {"value": "john@example.com", "start": 35, "end": 51, "mask_strategy": "partial"}
            ]
        }
        ```
        """
    def mask(self, text: builtins.str, detections: DetectionsByType) -> builtins.str:
        r"""
        Mask detected PII in text

        # Arguments
        * `text` - Original text
        * `detections` - Detection results from detect()

        # Returns
        Masked text with PII replaced
        """
    def process_nested(self, data: typing.Any, path: builtins.str) -> tuple[builtins.bool, typing.Any, DetectionsByType]:
        r"""
        Process nested data structures (dicts, lists, strings)

        # Arguments
        * `data` - Python object (dict, list, str, or other)
        * `path` - Current path in the structure (for logging)

        # Returns
        Tuple of (modified: bool, new_data: Any, detections: dict)
        """
